name: fingrow_mobile
description: FinGrow mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.5.5
  cupertino_icons: ^1.0.0

flutter:
  uses-material-design: true
